@startuml
'https://plantuml.com/class-diagram

abstract class AllModules

FavModules <|-- AllModules

class AllModules {
Object[] radioModule
num()
}

class FavModules {
Object[] radioModuleFav
num()
}
enum ListStatus {
FULL
EMPTY
}

@enduml